import type { SignupEntry } from "./types/Entry";

export const entries: SignupEntry[] = [
  {
    Timestamp: "2025-11-05 13:33",
    Gender: "MALE",
    "Country Code": "NZ",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "New Zealand",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-11-05 06:52",
    Gender: "FEMALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-11-04 09:14",
    Gender: "MALE",
    "Country Code": "GE",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Georgia",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-11-03 10:40",
    Gender: "MALE",
    "Country Code": "KE",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Kenya",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-11-02 08:51",
    Gender: "FEMALE",
    "Country Code": "IR",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Frontend masters",
    "Country name (from Country)": "Iran, Islamic Republic of",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-11-01 07:31",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-31 14:09",
    Gender: "FEMALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-31 14:05",
    Gender: "MALE",
    "Country Code": "BR",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "FREE CODE CAMP FORUM",
    "Source-Other": "",
    "Country name (from Country)": "Brazil",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V??",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-31 13:34",
    Gender: "MALE",
    "Country Code": "CR",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other":
      "I was in other thing like this but in spanish, I used ChatGPT to search for similar but in English",
    "Country name (from Country)": "Costa Rica",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-31 12:56",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "College",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-31 06:57",
    Gender: "MALE",
    "Country Code": "GH",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other":
      "I was reasearching on ChatGPT for platforms to gain experience in group projects.",
    "Country name (from Country)": "Ghana",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-30 02:54",
    Gender: "FEMALE",
    "Country Code": "KR",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Korea, Republic of",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 18:46",
    Gender: "FEMALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 14:59",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 14:18",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 12:58",
    Gender: "MALE",
    "Country Code": "SA",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "ChatGPT",
    "Country name (from Country)": "Saudi Arabia",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 12:47",
    Gender: "MALE",
    "Country Code": "SA",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "chatGPT told me about you.",
    "Country name (from Country)": "Saudi Arabia",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 04:09",
    Gender: "MALE",
    "Country Code": "ID",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "Gain real experience and also networking",
    Source: "OTHER",
    "Source-Other": "Skillcrush student community",
    "Country name (from Country)": "Indonesia",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-29 01:31",
    Gender: "MALE",
    "Country Code": "FR",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Chat GPT",
    "Country name (from Country)": "France",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-28 21:23",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V??",
    "Voyage Tier": "Tier 1",
  },
  {
    Timestamp: "2025-10-28 17:18",
    Gender: "MALE",
    "Country Code": "ES",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "I like code with people and gain experience",
    Source: "DEV.TO",
    "Source-Other": "",
    "Country name (from Country)": "Spain",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V??",
    "Voyage Tier": "Tier 2",
  },
  {
    Timestamp: "2025-10-28 11:33",
    Gender: "MALE",
    "Country Code": "NL",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Netherlands",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-28 11:07",
    Gender: "FEMALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-28 06:11",
    Gender: "MALE",
    "Country Code": "ZA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "South Africa",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-28 01:23",
    Gender: "MALE",
    "Country Code": "ZA",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "Gain Experience, Collaborating with Team",
    Source: "OTHER",
    "Source-Other": "ckissi developer-resources from git-hub",
    "Country name (from Country)": "South Africa",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-27 13:09",
    Gender: "FEMALE",
    "Country Code": "KE",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "i want a chance to excercise my data science skills",
    Source: "YOUTUBE",
    "Source-Other": "",
    "Country name (from Country)": "Kenya",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-26 12:10",
    Gender: "FEMALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-26 08:26",
    Gender: "FEMALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other":
      "I have skills but wants gain more experience through working on the projects, so wants to join chingu",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-26 06:23",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Skillcrush",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-26 05:56",
    Gender: "MALE",
    "Country Code": "ES",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other":
      "I'd love to meet people and stay in real projects to get experience. I'm currently a QA Tester in a Game company.",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Spain",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V59",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-26 04:50",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other":
      "I want to gain experience and i need friends who supports me in my journey and for share goals.",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-25 23:18",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Chatgpt",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-25 07:18",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "TWITTER",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-25 02:55",
    Gender: "FEMALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-24 18:06",
    Gender: "MALE",
    "Country Code": "DZ",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "discord server",
    "Country name (from Country)": "Algeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-24 12:35",
    Gender: "PREFER NOT TO SAY",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "Looking forward to dive into a team based project!",
    Source: "OTHER",
    "Source-Other": "The FrontEnd Masters Podcast",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-23 18:32",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "Learn industry standards",
    Source: "PERSONAL NETWORK",
    "Source-Other": "Roy Mugello",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-23 10:00",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-23 08:19",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "FREE CODE CAMP FORUM",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V??",
    "Voyage Tier": "Tier 1",
  },
  {
    Timestamp: "2025-10-23 04:00",
    Gender: "MALE",
    "Country Code": "MA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "Morocco",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V57,V58",
    "Voyage Tier": "Tier 1,Tier 1",
  },
  {
    Timestamp: "2025-10-22 20:53",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 20:42",
    Gender: "MALE",
    "Country Code": "GH",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "Ghana",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 20:39",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "from Francesca Sadikin at Frontend Master",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 13:04",
    Gender: "FEMALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 12:24",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 11:49",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 11:07",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V??",
    "Voyage Tier": "Tier 1",
  },
  {
    Timestamp: "2025-10-22 11:03",
    Gender: "MALE",
    "Country Code": "BR",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "ChatGPT",
    "Country name (from Country)": "Brazil",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 09:23",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 02:29",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-22 00:12",
    Gender: "FEMALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 23:19",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 20:56",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "OTHER",
    "Goal-Other": "Refresh my Scrum Master knowledge.",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 19:38",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 17:15",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 15:58",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V59",
    "Voyage Tier": "Tier 2",
  },
  {
    Timestamp: "2025-10-21 15:38",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 11:25",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 09:56",
    Gender: "FEMALE",
    "Country Code": "DE",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "FrontendMasters",
    "Country name (from Country)": "Germany",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-21 04:28",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-18 17:35",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other":
      "I’ve completed a chingu project before, just wanted to join the group to potentially give back, and network.",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V52",
    "Voyage Tier": "Tier 2",
  },
  {
    Timestamp: "2025-10-18 12:33",
    Gender: "MALE",
    "Country Code": "PL",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "DEV.TO",
    "Source-Other": "",
    "Country name (from Country)": "Poland",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-18 08:56",
    Gender: "MALE",
    "Country Code": "HU",
    Timezone: "",
    Goal: "OTHER",
    "Goal-Other": "Get a job in the field as web developer",
    Source: "LinkedIn",
    "Source-Other": "Google Search, Email from previous attempt",
    "Country name (from Country)": "Hungary",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-18 08:35",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "OTHER",
    "Goal-Other": "",
    Source: "YOUTUBE",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-18 08:31",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "ChatGPT recommended",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-17 21:42",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-17 20:02",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "an LLM referred me",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-17 18:59",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-17 12:35",
    Gender: "FEMALE",
    "Country Code": "KE",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "from my undergraduate friend",
    "Country name (from Country)": "Kenya",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-17 05:04",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-17 03:09",
    Gender: "MALE",
    "Country Code": "NL",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "FREE CODE CAMP FORUM",
    "Source-Other": "",
    "Country name (from Country)": "Netherlands",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 21:49",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 19:47",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 17:51",
    Gender: "MALE",
    "Country Code": "AR",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "i asked to ChatGPT how can i do pair programing",
    "Country name (from Country)": "Argentina",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 15:32",
    Gender: "FEMALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other":
      "Earned a certification in Introduction to the Scrum Master Profession on Coursera; currently completing the Scrum Master Capstone.",
    Source: "OTHER",
    "Source-Other": "From a product manager friend",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 15:28",
    Gender: "FEMALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-16 12:55",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Stephanie Cully Suggested me.",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:35",
    Gender: "FEMALE",
    "Country Code": "ZA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "South Africa",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:32",
    Gender: "MALE",
    "Country Code": "GH",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Ghana",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-16 11:28",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:24",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Job Hackers",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:22",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:22",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:21",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "OTHER",
    "Goal-Other": "Gain more knowledge and change careers",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:17",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:16",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "No completed certifications",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:12",
    Gender: "MALE",
    "Country Code": "TH",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Thailand",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:08",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:06",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:06",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "I don't have any certificates",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 11:04",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-16 02:14",
    Gender: "MALE",
    "Country Code": "IT",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Italy",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-15 21:33",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "chatgpt",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-15 19:28",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "Also network with others",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-14 15:52",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-14 11:45",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-14 11:45",
    Gender: "MALE",
    "Country Code": "JM",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Jamaica",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V59",
    "Voyage Tier": "Tier 1",
  },
  {
    Timestamp: "2025-10-14 11:39",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-14 11:23",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-14 08:32",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-13 13:08",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other":
      "to get to know about real industry projects and needs and work ethics",
    Source: "OTHER",
    "Source-Other": "chatgpt",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-13 06:50",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-13 05:23",
    Gender: "FEMALE",
    "Country Code": "KE",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Kenya",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-13 03:49",
    Gender: "FEMALE",
    "Country Code": "DK",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Denmark",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 2",
  },
  {
    Timestamp: "2025-10-13 01:24",
    Gender: "FEMALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "OTHER",
    "Goal-Other": "Looking to land on a job",
    Source: "OTHER",
    "Source-Other": "From my bookmark",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 16:09",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Brother",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 14:36",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 12:16",
    Gender: "MALE",
    "Country Code": "PL",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "chatgpt",
    "Country name (from Country)": "Poland",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 07:50",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "FREE CODE CAMP FORUM",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 06:17",
    Gender: "MALE",
    "Country Code": "VN",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other":
      "I learned about Chingu from a developer community and ChatGPT recommendation.",
    "Country name (from Country)": "Vietnam",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 03:27",
    Gender: "MALE",
    "Country Code": "NP",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Vercel",
    "Country name (from Country)": "Nepal",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 03:21",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-12 03:15",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-11 12:59",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-11 12:07",
    Gender: "MALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "ChatGPT",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-11 09:57",
    Gender: "MALE",
    "Country Code": "IT",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "",
    "Country name (from Country)": "Italy",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-11 09:31",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-11 08:26",
    Gender: "FEMALE",
    "Country Code": "JP",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Japan",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-10 06:20",
    Gender: "FEMALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-10 04:14",
    Gender: "FEMALE",
    "Country Code": "DE",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "Germany",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-09 14:45",
    Gender: "MALE",
    "Country Code": "UA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "Ukraine",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-09 14:15",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-08 11:52",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "YOUTUBE",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-08 11:50",
    Gender: "MALE",
    "Country Code": "IR",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "YOUTUBE",
    "Source-Other": "",
    "Country name (from Country)": "Iran, Islamic Republic of",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-08 09:41",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other":
      "I completed the Google certification program through Coursera in Project Management.  I've done their tutorials and projects but thats all guided.  I'd like to gain experience watching someone actually perform the dutied and take notes on how they function and help where I can. I believe I have the soft skills and energy to do this right and I would love to watch a pro in action so I can get a feel of what the meetings truly look and feel like.",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-08 08:58",
    Gender: "MALE",
    "Country Code": "UG",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "Non",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Uganda",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-08 00:57",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other":
      "I want to gain hands-on experience working in a team environment that follows real-world Agile and Scrum practices. I’m looking forward to collaborating with other developers, improving my code quality, and learning how tasks are managed and delivered in a professional setup",
    Source: "OTHER",
    "Source-Other": "Chat gpt",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-07 10:32",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Brother",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-07 10:18",
    Gender: "MALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Chatgpt",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-07 03:02",
    Gender: "MALE",
    "Country Code": "AU",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Australia",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-07 02:54",
    Gender: "MALE",
    "Country Code": "PH",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "AI conversation",
    "Country name (from Country)": "Philippines",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-10-06 18:22",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Discord",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-06 12:53",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-05 14:03",
    Gender: "MALE",
    "Country Code": "ID",
    Timezone: "",
    Goal: "OTHER",
    "Goal-Other":
      "get portofolio for next.js front end web dev and find remote job",
    Source: "OTHER",
    "Source-Other": "Chatgpt",
    "Country name (from Country)": "Indonesia",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-05 13:35",
    Gender: "FEMALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Product Owner",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-05 11:14",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "FREE CODE CAMP FORUM",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-04 22:59",
    Gender: "FEMALE",
    "Country Code": "NZ",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other":
      "I think this is the right step in gaining and building projects",
    Source: "The Job Hackers",
    "Source-Other": "",
    "Country name (from Country)": "New Zealand",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-04 07:50",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Tiktok",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-03 22:48",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-03 17:20",
    Gender: "MALE",
    "Country Code": "SE",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "AI",
    "Country name (from Country)": "Sweden",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-03 06:23",
    Gender: "MALE",
    "Country Code": "DE",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "",
    "Country name (from Country)": "Germany",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-02 17:52",
    Gender: "FEMALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "TWITTER",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-02 16:12",
    Gender: "MALE",
    "Country Code": "IQ",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Iraq",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-02 15:14",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other":
      "I came to know about Chingu through Chat gpt when i was searching about some great platforms to build projects with others.",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-02 05:56",
    Gender: "MALE",
    "Country Code": "MA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Morocco",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-10-01 19:10",
    Gender: "MALE",
    "Country Code": "BR",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Brazil",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-30 11:14",
    Gender: "MALE",
    "Country Code": "IT",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Reddit",
    "Country name (from Country)": "Italy",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-29 12:41",
    Gender: "MALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-29 03:45",
    Gender: "FEMALE",
    "Country Code": "TW",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other":
      "Hope to gian more experience about cooperate with overseas people to work in an overseas company in the near future.",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "Taiwan, Province of China",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-28 19:11",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other":
      "ChatGPT mentioned when asked our how to find real life experience.",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-28 18:45",
    Gender: "MALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-28 03:18",
    Gender: "MALE",
    "Country Code": "PK",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Pakistan",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-27 07:33",
    Gender: "FEMALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "i want to build projects confidently on my own",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-27 00:36",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-26 17:58",
    Gender: "FEMALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-26 14:31",
    Gender: "MALE",
    "Country Code": "GR",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "YOUTUBE",
    "Source-Other": "",
    "Country name (from Country)": "Greece",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-26 07:08",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-25 13:54",
    Gender: "FEMALE",
    "Country Code": "ZA",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "South Africa",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-09-25 03:24",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "FrontEnd Masters",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-25 02:20",
    Gender: "MALE",
    "Country Code": "EG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "my friend",
    "Country name (from Country)": "Egypt",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-25 01:57",
    Gender: "MALE",
    "Country Code": "LB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "Lebanon",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-24 12:37",
    Gender: "MALE",
    "Country Code": "GB",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United Kingdom",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-24 01:52",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Python",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-23 22:38",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "GitHub",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 2",
  },
  {
    Timestamp: "2025-09-23 18:40",
    Gender: "MALE",
    "Country Code": "EG",
    Timezone: "",
    Goal: "GET OUT OF TUTORIAL PURGATORY",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "random linkedin post",
    "Country name (from Country)": "Egypt",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-23 14:20",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "MEDIUM",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V56",
    "Voyage Tier": "Tier 2",
  },
  {
    Timestamp: "2025-09-23 05:57",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "NETWORK WITH SHARED GOALS",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "A blog post",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-23 05:17",
    Gender: "PREFER NOT TO SAY",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other":
      "Want to get more real-world UX/UI Design experience and learn from teammates.",
    Source: "PERSONAL NETWORK",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-22 14:26",
    Gender: "FEMALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "from a friend",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-09-22 08:05",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "From a Friend",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-20 22:40",
    Gender: "FEMALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-20 08:14",
    Gender: "FEMALE",
    "Country Code": "CA",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "ChatGPT",
    "Country name (from Country)": "Canada",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V58,V58",
    "Voyage Tier": "Tier 3,Tier 3",
  },
  {
    Timestamp: "2025-09-19 21:04",
    Gender: "MALE",
    "Country Code": "PK",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "",
    "Country name (from Country)": "Pakistan",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-19 16:06",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-19 01:39",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "Scrum Master",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-18 21:17",
    Gender: "FEMALE",
    "Country Code": "EC",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "I searched in chatgpt",
    "Country name (from Country)": "Ecuador",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-18 17:20",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "ACCELERATE LEARNING",
    "Goal-Other": "",
    Source: "YOUTUBE",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V??",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-09-18 13:02",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "V58",
    "Voyage Tier": "Tier 3",
  },
  {
    Timestamp: "2025-09-18 11:57",
    Gender: "MALE",
    "Country Code": "US",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "United States",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-16 20:41",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "OTHER",
    "Source-Other": "Brother",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-16 12:24",
    Gender: "MALE",
    "Country Code": "IN",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "GOOGLE SEARCH",
    "Source-Other": "",
    "Country name (from Country)": "India",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-16 10:45",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "",
    Source: "LinkedIn",
    "Source-Other": "",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "",
    "Voyage Role": "UI/UX Designer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
  {
    Timestamp: "2025-09-16 10:44",
    Gender: "MALE",
    "Country Code": "NG",
    Timezone: "",
    Goal: "GAIN EXPERIENCE",
    "Goal-Other": "Accelerate Experience and networking",
    Source: "LinkedIn",
    "Source-Other": "My Friend",
    "Country name (from Country)": "Nigeria",
    "Solo Project Tier": "",
    "Role Type": "Web",
    "Voyage Role": "Developer",
    "Voyage (from Voyage Signups)": "",
    "Voyage Tier": "",
  },
];
